### ISSUE TITLE
Default DB size

### ISSUE THREAD

**Issue by GreenSaaSDev** [salesforce-misc/Data-Lake-for-Nonprofits#6]
I provisioned my non-profit client with a Data Lake for only 5 objects and specified using the Amplify application to only extract 1x/month.  At time of initial extract there were roughly 1.1M records distributed across those 5 objects.  The resulting Postgres database class was db.m6g.large, which I understand is not eligible for the free tier usage.  I have since stopped the production database service, temporarily, to not continue to incur costs that are now running in the $100s/month for this client (annualized that will far exceed the $1k in credits offered for eligible Non-profits).  Broad question is: **Is there a way to ensure that a Micro db class will be provisioned to keep the client in the free-tier?**  And secondarily, what number of objects drives the provisioning of a large db so I can avoid this in the future?

**Comment by GreenSaaSDev** [comment]
![image](https://user-images.githubusercontent.com/97256018/201184234-d8f8c9a1-f1a7-4d6c-9994-f1a3a05a25d6.png)

As you can see, there's only 7GB of data so this should have fallen into the free tier.

AWS Free Tier with Amazon RDS
750 hours of Amazon RDS Single-AZ db.t2.micro, db.t3.micro, and db.t4g.micro Instances usage running MySQL, MariaDB, PostgreSQL databases each month. If running more than one instance, usage is aggregated across instance classes.
750 hours of Amazon RDS Single-AZ db.t2.micro Instance usage running SQL Server (running SQL Server Express Edition) each month.
20 GB of General Purpose (SSD) DB Storage*
20 GB of backup storage for your automated database backups and any user-initiated DB Snapshots*
* Backup storage is free up to 20 GB or the size of your DB storage, whichever is less, and requires you to have at least one DB instance running in your account. If you exceed these limits, or if you terminate all DB instances in your account, backup storage will be charged at standard RDS rates.

**Comment by simsek97** [comment]
There are multiple reasons for why the default database is selected to be not in Free Tier by design. However, you can change the database instance class in the datastore CloudFormation template in the link below after cloning the repo
https://github.com/salesforce-misc/Data-Lake-for-Nonprofits/blob/main/infra/cf/datastore.yaml#L352
and build it locally and update your Amplify hosting with the zip file.
Regarding how to build the application locally, you can follow this documentation.
https://github.com/salesforce-misc/Data-Lake-for-Nonprofits/blob/main/docs/Development.md

**Comment by tweeksPHL** [comment]
Hello, we appreciate the desire to change the database instance. I understand your logic and the need. There were many reasons why the architecture we launched with was selected. Though we understand that it might not always be the right starting point for every organization. Our intention is to offer a rich, easy-to-use application to as many AWS & SF users as possible in order to get them started on a multi-cloud approach. In the spirit of open source, we are encouraging those with needs that differ from the base application to fork the code and make changes locally with their own internal teams or an implementation consultant utilizing the supporting documentation [](https://github.com/salesforce-misc/Data-Lake-for-Nonprofits/blob/main/docs/Development.md). If you decide to complete this work, please let us know as we would like to follow. We hope in the future to have capacity to further develop the application and have noted this as a future feature request. Thank you for the engagement.

**Comment by GreenSaaSDev** [comment]
We built this locally but there's another setting that needs to change (MaxAllocatedSize).  Can @simsek97 edit his response to show that line as well?

Resource handler returned message: "Invalid max storage size for engine name postgres and storage type gp2: **64000** (Service: Rds, Status Code: 400, Request ID: 683243bc-80e2-42b6-ad93-7f1675c65b71)" (RequestToken: 2252bd91-47c4-7060-94d1-653414271079, HandlerErrorCode: InvalidRequest)

**Comment by simsek97** [comment]
There is a parameter called `MaxAllocatedStorage` below which you will need to update based on the your configuration.
https://github.com/salesforce-misc/Data-Lake-for-Nonprofits/blob/main/infra/cf/datastore.yaml#L358
