### ISSUE TITLE
Deprovisioning

### ISSUE THREAD

**Issue by GreenSaaSDev** [salesforce-misc/Data-Lake-for-Nonprofits#7]
The setup tool creates many resources that do not appear to be supported with AWS Free Tier including but not limited to:
dbm6g.large (RDS)
automated backups that incur Storage costs
VPCs incurring cost per VPC hour

It is far more difficult to deprovision these elements when a lake is created against a sandbox for instance and needs to be deleted to ensure there is no duplicate billing.  Specifically when trying to delete VPCs multiple ENIs are in place that cannot be deleted because they are in use.  From the forums it seems you must download the AWS CLI to discover and remove these associations.  Please include a wizard for full tear down of Data Lakes to make it easier to manage billing

**Comment by simsek97** [comment]
It is challenging to delete the data lake using CloudFormation console. Due to this reason, we have a `delete-datalake` command that you can use in your local repo following this documentation.
https://github.com/salesforce-misc/Data-Lake-for-Nonprofits/blob/main/docs/e2eTesting.md#how-to-delete-a-datalake
