### ISSUE TITLE
Received response status [FAILED] from custom resource. 

### ISSUE THREAD

**Issue by markdamo1** [salesforce-misc/Data-Lake-for-Nonprofits#8]
When setting up a new instance when I get to the steps to build out the Datalake the setup fails on the first step to set up the S3 buckets. I've double check my user has the correct permissions and retried the setup several times but I keep hitting the same issue.

![7e440b5c-31ee-4b9d-9a20-53065b897076](https://user-images.githubusercontent.com/50417541/206458595-b037e6ac-977a-4225-b245-c66250b6432e.jpg)

I found the stack trace and see this message 

![e26b1c5c-ae75-45d7-a183-ca7d9cbbb0cb](https://user-images.githubusercontent.com/50417541/206458691-1a5ac0d5-e0d2-4294-8242-f39c8a68995a.jpg)

The CloudWatch logs show this message:
![image](https://user-images.githubusercontent.com/50417541/206458819-0517830a-2121-4892-bfe5-f6b60c8f457a.png)

Im not sure what I need to do to resolve this?

**Comment by simsek97** [comment]
Seems like you edited the application to prompt a username and password which blocks copying the assets. The application should be publicly available so that the assets can be copied.

![2022-12-08_22-51-40](https://user-images.githubusercontent.com/8814950/206620521-1a75cdef-2993-4bd8-be3f-2a2a04499cbd.png)

**Comment by markdamo1** [comment]
Indeed that did fix the issue. Thanks
